name: Events Demo 1
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get data
        run: echo ABC=123 >> $GITHUB_ENV
      - name: If
        if: env.ABC == '123'
        run: echo "If"
      - name: Else
        if: env.ABC != '123'
        run: echo "Else"
