name: Events Demo 1
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get data
        run: export ABC = "123"
      - name: If
        if: env.ABC == "123"
        run: echo "If"
      - name: Else
        if: env.ABC != "123"
        run: echo "Else"
